const Pairs = [
  [{ word: "Lock", phonetic: "lˈɑːk" }, { word: "Rock", phonetic: "ɹˈɑːk" }],
  [{ word: "Wash", phonetic: "wˈɑːʃ" }, { word: "Wish", phonetic: "wˈɪʃ" }],
  [{ word: "Dish", phonetic: "dˈɪʃ" }, { word: "Dash", phonetic: "dˈæʃ" }],
  [{ word: "Lose", phonetic: "lˈuːz" }, { word: "Loose", phonetic: "lˈuːs" }],
  [{ word: "Advice", phonetic: "ɐdvˈaɪs" }, { word: "Advise", phonetic: "ɐdvˈaɪz" }],
  [{ word: "Affect", phonetic: "ɐfˈɛkt" }, { word: "Effect", phonetic: "ɪfˈɛkt" }],
  [{ word: "Compliment", phonetic: "kˈɑːmplɪmənt" }, { word: "Complement", phonetic: "kˈɑːmplɪmənt" }],
  [{ word: "Hang", phonetic: "hˈæŋ" }, { word: "Hung", phonetic: "həŋ" }],
  [{ word: "Price", phonetic: "prīs" }, { word: "Prize", phonetic: "prīz" }],
  [{ word: "Bed", phonetic: "bed" }, { word: "Bad", phonetic: "bad" }],
  [{ word: "Sing", phonetic: "siŋ" }, { word: "Thing", phonetic: "thiŋ" }],
  [{ word: "Sick", phonetic: "sik" }, { word: "Thick", phonetic: "thik" }],
  [{ word: "She", phonetic: "shē" }, { word: "Sea", phonetic: "sē" }],
  [{ word: "Best", phonetic: "best" }, { word: "Vest", phonetic: "vest" }],
  [{ word: "Sue", phonetic: "sü" }, { word: "Shoe", phonetic: "shü" }],
  [{ word: "Glass", phonetic: "glas" }, { word: "Grass", phonetic: "gras" }],
  [{ word: "Hat", phonetic: "hat" }, { word: "Fat", phonetic: "fat" }, { word: "Rat", phonetic: "rat" }],
  [{ word: "Lip", phonetic: "lip" }, { word: "Rip", phonetic: "rip" }],
  [{ word: "Deep", phonetic: "dēp" }, { word: "Dip", phonetic: "dip" }],
  [{ word: "Lice", phonetic: " līs" }, { word: "Rice", phonetic: "rīs" }],
  [{ word: "Right", phonetic: "rīt" }, { word: "Light", phonetic: "līt" }, { word: "Late", phonetic: "lāt" }],
  [{ word: "Long", phonetic: "lȯŋ" }, { word: "Wrong", phonetic: "rȯŋ" }],
  [{ word: "Walk", phonetic: "wȯk" }, { word: "Work", phonetic: "wərk" }],
  [{ word: "Very", phonetic: "ver-ē" }, { word: "Berry", phonetic: "ber-ē" }],
  [{ word: "Fan", phonetic: "fan" }, { word: "Van", phonetic: "van" }, { word: "Ban", phonetic: "ban" }],
  [{ word: "Paper", phonetic: "pā-pər" }, { word: "Pepper", phonetic: "pe-pər" }],
  [{ word: "Ship", phonetic: "ship" }, { word: "Sheep", phonetic: "shēp" }],
  [{ word: "Shit", phonetic: "shit" }, { word: "Sheet", phonetic: "shēt" }],
  [{ word: "Bitch", phonetic: "bich" }, { word: "Beach", phonetic: "bēch" }, { word: "Peach", phonetic: "pēch" }],
  [{ word: "Button", phonetic: "bə-tᵊn" }, { word: "Bottom", phonetic: "bä-təm" }],
  [{ word: "Feel", phonetic: "fēl" }, { word: "Fill", phonetic: "fil" }],
  [{ word: "Bold", phonetic: "bōld" }, { word: "Bald", phonetic: "bȯld" }],
  [{ word: "Trader", phonetic: "trā-dər" }, { word: "Traitor", phonetic: "trā-tər" }],
  [{ word: "Diary", phonetic: "dī-(ə-)rē" }, { word: "Dairy", phonetic: "der-ē" }],
  [{ word: "Chew", phonetic: "chü" }, { word: "Shoe", phonetic: "shü" }],
  [{ word: "Break", phonetic: "brāk" }, { word: "Brake", phonetic: "brāk" }],
  [{ word: "Illusion", phonetic: "i-ˈlü-zhən" }, { word: "Allusion", phonetic: "ə-ˈlü-zhən" }],
  [{ word: "Intention", phonetic: "in-ˈten(t)-shən" }, { word: "Attention", phonetic: "ə-ˈten(t)-shən" }],
  [{ word: "Bill", phonetic: "bˈɪl" }, { word: "Bell", phonetic: "bˈɛl" }],
  [{ word: "Fill", phonetic: "fˈɪl" }, { word: "Fell", phonetic: "fˈɔːl" }, { word: "Feel", phonetic: "fˈiːl" }],
  [{ word: "Hill", phonetic: "hˈɪl" }, { word: "Hell", phonetic: "hˈɛl" }],
  [{ word: "Howl", phonetic: "hˈaʊl" },{ word: "Hole", phonetic: "hˈoʊl" }],
  [{ word: "Eerie", phonetic: "ɪɹi" }, { word: "Erie", phonetic: "iəɹi" }],
  [{ word: "Incite", phonetic: "ɪnsˈaɪt" }, { word: "Inside", phonetic: "ɪnsˈaɪd" }],
  [{ word: "Decease", phonetic: "dᵻsˈiːs" }, { word: "Disease", phonetic: "dɪzˈiːz" }],
  [{ word: "Scene", phonetic: "sˈiːn" }, { word: "Seem", phonetic: "sˈiːm" }, { word: "Sin", phonetic: "sˈɪn" }],
  [{ word: "Scene", phonetic: "sˈiːn" }, { word: "Seen", phonetic: "sēn" }, { word: "Sin", phonetic: "sˈɪn" }],
  [{ word: "Sawn", phonetic: "sȯn" }, { word: "Son", phonetic: "sən" }],
  [{ word: "Mayor", phonetic: "mā-ər" }, { word: "Major", phonetic: "mā-jər" }],
  [{ word: "Green", phonetic: "grēn" }, { word: "Grain", phonetic: "grān" }, { word: "Grin", phonetic: "grin" }],
  [{ word: "Ground", phonetic: "grau̇nd" }, { word: "Grown", phonetic: "grōn" }, { word: "Groin", phonetic: "grȯin" }],
  [{ word: "Star", phonetic: "stär" }, { word: "Stair", phonetic: "ster" }],
  [{ word: "Will", phonetic: "wil" }, { word: "Well", phonetic: "wel" }],
  [{ word: "Bliss", phonetic: "blis" }, { word: "Bless", phonetic: "bles" }],
  [{ word: "Hid", phonetic: "hid" }, { word: "Head", phonetic: "hed" }],
  [{ word: "Win", phonetic: "win" }, { word: "When", phonetic: "(h)wen" }, { word: "Won", phonetic: "wən" }],
  [{ word: "Size", phonetic: "sīz" }, { word: "Sides", phonetic: "saɪdz" }],
  [{ word: "Vote", phonetic: "vōt" }, { word: "What", phonetic: "(h)wät" }],
  [{ word: "Golf", phonetic: "gälf" }, { word: "Gulf", phonetic: "gəlf" }],
  [{ word: "Do", phonetic: "dü" }, { word: "Dough", phonetic: "dō" }],
  [{ word: "Pushy", phonetic: "pu̇-shē" }, { word: "Pussy", phonetic: "pu̇-sē" }],
  [{ word: "Breast", phonetic: "brest" }, { word: "Breath", phonetic: "breth" }],
  [{ word: "Thief", phonetic: "thēf" }, { word: "Teeth", phonetic: "tēth" }],
  [{ word: "Course", phonetic: "kȯrs" }, { word: "Curse", phonetic: "kərs" }],
  [{ word: "Fat", phonetic: "fat" }, { word: "Fart", phonetic: "färt" }],
  [{ word: "That", phonetic: "t͟hat" }, { word: "Vat", phonetic: "vat" }],
  [{ word: "Pawn", phonetic: "pȯn" }, { word: "Porn", phonetic: "pȯrn" }],
  [{ word: "West", phonetic: "west" }, { word: "Waste", phonetic: "wāst" }],
  [{ word: "West", phonetic: "west" }, { word: "Vast", phonetic: "vast" }],
  [{ word: "Sheet", phonetic: "shēt" }, { word: "Shit", phonetic: "shit" }],
  [{ word: "Seat", phonetic: "sēt" }, { word: "Sit", phonetic: "sit" }],
  [{ word: "Soup", phonetic: "süp" }, { word: "Soap", phonetic: "sōp" }],
  [{ word: "Plan", phonetic: "plan" }, { word: "Plane", phonetic: "plān" }],
  [{ word: "Road", phonetic: "rōd" }, { word: "Rod", phonetic: "räd" }, { word: "Rad", phonetic: "rad" }],
  [{ word: "Latter", phonetic: "la-tər" }, { word: "Ladder", phonetic: "la-dər" }],
  [{ word: "Latter", phonetic: "la-dər" }, { word: "Later", phonetic: "lā-tər" }],
  [{ word: "Leader", phonetic: "lē-dər" }, { word: "Liter", phonetic: "lē-tər" }],
  [{ word: "Letter", phonetic: "le-tər" }, { word: "Litter", phonetic: "li-tər" }],
  [{ word: "Letter", phonetic: "le-tər" }, { word: "Latter", phonetic: "la-dər" }],
  [{ word: "Desert", phonetic: "de-zərt" }, { word: "Dessert", phonetic: "di-ˈzərt " }],
  [{ word: "Conform", phonetic: "kən-ˈfȯrm" }, { word: "Confirm", phonetic: "kən-ˈfərm" }],
  [{ word: "Ask", phonetic: "ask" }, { word: "Axe", phonetic: "aks" }],
  [{ word: "Fire", phonetic: "fī(-ə)r" }, { word: "Fired", phonetic: "fī(-ə)rd" }],
  [{ word: "Older", phonetic: "ōl-dər" }, { word: "Order", phonetic: "ȯr-dər" }],
  [{ word: "Man", phonetic: "man" }, { word: "Men", phonetic: "men" }],
  [{ word: "Woman", phonetic: "wu̇-mən" }, { word: "Women", phonetic: "wi-​mən" }],
  [{ word: "Fill", phonetic: "fil" }, { word: "Feel", phonetic: "fēl" }],
  [{ word: "Breath", phonetic: "breth" }, { word: "Brief", phonetic: "brēf" }],
  [{ word: "Rid", phonetic: "rid" }, { word: "Raid", phonetic: "rād" }],
  [{ word: "Doll", phonetic: "däl" }, { word: "Dull", phonetic: "dəl" }],
  [{ word: "Fast", phonetic: "fast" }, { word: "First", phonetic: "fərst" }],
  [{ word: "Coal", phonetic: "kōl" }, { word: "Cool", phonetic: "kül" }, { word: "Call", phonetic: "kȯl" }],
  [{ word: "Meadow", phonetic: "me-(ˌ)dō" }, { word: "Medal", phonetic: "me-dᵊl" }],
  [{ word: "Show", phonetic: "shō" }, { word: "So", phonetic: "sō" }],
  [{ word: "So", phonetic: "sō" }, { word: "Saw", phonetic: "sȯ" }],
  [{ word: "So", phonetic: "sō" }, { word: "Soul", phonetic: "sōl" }],
  [{ word: "No", phonetic: "nō" }, { word: "Now", phonetic: "nau̇" }],
  [{ word: "Gone", phonetic: "gȯn" }, { word: "Gun", phonetic: "gən" }],
  [{ word: "Toes", phonetic: "tōz" }, { word: "Those", phonetic: "t͟hōz" }],
  [{ word: "Mess", phonetic: "mes" }, { word: "Meth", phonetic: "meth" }],
  [{ word: "Ass", phonetic: "as" }, { word: "As", phonetic: "əz" }],
  [{ word: "Ass", phonetic: "as" }, { word: "Ash", phonetic: "ash" }],
  [{ word: "Pose", phonetic: "pōz" }, { word: "Pause", phonetic: "pȯz" }],
  [{ word: "Bag", phonetic: "bag" }, { word: "Beg", phonetic: "beg" }],
  [{ word: "Rent", phonetic: "rent" }, { word: "Rant", phonetic: "rant" }],
  [{ word: "Does", phonetic: "dəz" }, { word: "Those", phonetic: "t͟hōz" }],
  [{ word: "Chris", phonetic: "kris" }, { word: "Crease", phonetic: "krēs" }],
  [{ word: "Third", phonetic: "thərd" }, { word: "Turd", phonetic: "tərd" }],
  [{ word: "Ball", phonetic: "bȯl" }, { word: "Bowl", phonetic: "bōl" }],
  [{ word: "Broke", phonetic: "brōk" }, { word: "Brooke", phonetic: "bru̇k" }],
  [{ word: "Broke", phonetic: "brōk" }, { word: "Block", phonetic: "bläk" }],
  [{ word: "Block", phonetic: "bläk" }, { word: "Black", phonetic: "blak" }],
  [{ word: "Ion", phonetic: "ī-ən" }, { word: "Iron", phonetic: "ī(-ə)rn" }],
  [{ word: "Eat", phonetic: "ēt" }, { word: "Heat", phonetic: "hēt" }],
  [{ word: "Filling", phonetic: "fi-liŋ" }, { word: "Filing", phonetic: "fī-liŋ" }, { word: "Failing", phonetic: "fā-liŋ" }],
  [{ word: "Air", phonetic: "er" }, { word: "Hair", phonetic: "her" }],
  [{ word: "Hair", phonetic: "her" }, { word: "Her", phonetic: "(h)ər" }],
  [{ word: "Heal", phonetic: "hēl" }, { word: "Hill", phonetic: "hil" }, { word: "Ill", phonetic: "il" }, { word: "Eel", phonetic: "ēl" }],
  [{ word: "Poll", phonetic: "pōl" }, { word: "Paul", phonetic: "pȯl" }],
  [{ word: "Sock", phonetic: "säk" }, { word: "Suck", phonetic: "sək" }],
  [{ word: "Fox", phonetic: "fäks" }, { word: "Fucks", phonetic: "fəks" }],
  [{ word: "Folks", phonetic: "fōks" }, { word: "Forks", phonetic: "fȯrks" }],
  [{ word: "Source", phonetic: "sȯrs" }, { word: "Sauce", phonetic: "sȯs" }],
  [{ word: "Discuss", phonetic: "di-ˈskəs" }, { word: "Disgust", phonetic: "di-ˈskəst" }],
  [{ word: "Switch", phonetic: "swich" }, { word: "Swish", phonetic: "swish" }],
  [{ word: "Close", phonetic: "klōz" }, { word: "Claws", phonetic: "klȯz" }],
  [{ word: "Tall", phonetic: "tȯl" }, { word: "Toll", phonetic: "tōl" }],
  [{ word: "Atom", phonetic: "a-təm" }, { word: "Adam", phonetic: "a-dəm" }],
  [{ word: "Savor", phonetic: "sā-vər" }, { word: "Savior", phonetic: "sāv-yər" }, { word: "Saver", phonetic: "sāvər" }],
  [{ word: "Met", phonetic: "met" }, { word: "Meat", phonetic: "mēt" }],
  [{ word: "Russian", phonetic: "rə-shən" }, { word: "Ration", phonetic: "ra-shən" }],
  [{ word: "Root", phonetic: "rüt" }, { word: "Rot", phonetic: "rät" }],
  [{ word: "Raider", phonetic: "rā-dər" }, { word: "Radar", phonetic: "rā-ˌdär" }],
  [{ word: "Martyr", phonetic: "mär-tər" }, { word: "Murder", phonetic: "mər-dər" }],
  [{ word: "Trust", phonetic: "trəst" }, { word: "Thrust", phonetic: "thrəst" }],
  [{ word: "List", phonetic: "list" }, { word: "Least", phonetic: "lēst" }],
  [{ word: "Take", phonetic: "tāk" }, { word: "Tech", phonetic: "tek" }],
  [{ word: "Sink", phonetic: "siŋk" }, { word: "Think", phonetic: "thiŋk" }],
  [{ word: "Prism", phonetic: "pri-zəm" }, { word: "Prison", phonetic: "pri-zᵊn" }],
  [{ word: "Cot", phonetic: "kät" }, { word: "Caught", phonetic: "kȯt" }],
  [{ word: "Laugh", phonetic: "laf" }, { word: "Loaf", phonetic: "lōf" }],
  [{ word: "Knotty", phonetic: "nä-tē" }, { word: "Naughty", phonetic: "nȯ-tē" }],
  [{ word: "Shart", phonetic: "shärt" }, { word: "Chart", phonetic: "chärt" }],
];
