const Pairs = [
  ["Lock", "Rock"],
  ["Wash", "Wish"],
  ["Dish", "Dash"],
  ["Lose", "Loose"],
  ["Advice", "Advise"],
  ["Affect", "Effect"],
  ["Compliment", "Complement"],
  ["Hang", "Hung"],
  ["Price", "Prize"],
  ["Bed", "Bad"],
  ["Sing", "Thing"],
  ["Sick", "Thick"],
  ["She", "Sea"],
  ["Best", "Vest"],
  ["Sue", "Shoe"],
  ["Glass", "Grass"],
  ["Hat", "Fat", "Rat"],
  ["Lip", "Rip"],
  ["Deep", "Dip"],
  ["Lice", "Rice"],
  ["Right", "Light", "Late"],
  ["Long", "Wrong"],
  ["Walk", "Work"],
  ["Very", "Berry"],
  ["Fan", "Van", "Ban"],
  ["Paper", "Pepper"],
  ["Ship", "Sheep"],
  ["Shit", "Sheet"],
  ["Bitch", "Beach", "Peach"],
  ["Button", "Bottom"],
  ["Feel", "Fill"],
  ["Bold", "Bald"],
  ["Trader", "Traitor"],
  ["Diary", "Dairy"],
  ["Chew", "Shoe"],
  ["To", "Too"],
  ["Break", "Brake"],
  ["Illusion", "Allusion"],
  ["Intention", "Attention"],
  ["Bill", "Bell"],
  ["Fill", "Fell", "Feel"],
  ["Hill", "Hell", "Hole"],
  ["Eerie", "Erie"],
  ["Incite", "Inside"],
  ["Decease", "Disease"],
  ["Seem", "Seam", "Sim"],
  ["Scene", "Seen", "Sin"],
  ["Mayor", "Major"],
  ["Green", "Grain", "Grin"],
  ["Groan", "Grown"],
  ["Star", "Stair", "Stare"], // Same?
  ["Will", "Well"],
  ["Bliss", "Bless"],
  ["Hid", "Head"],
  ["Win", "When", "Won"],
  ["Size", "Sides"],
  ["Vote", "What"],
  ["Golf", "Gulf", "Gulp"],
  ["Do", "Dough"],
  ["Pushy", "Pussy", "Puffy"],
  ["Breast", "Breath"],
  ["Thief", "Teeth"],
  ["Course", "Curse"],
  ["Fat", "Fart", "Vat"],
  ["That", "Vat"],
  ["Pawn", "Porn"],
  ["West", "Waste", "Waist"], //same?
  ["Sheet", "Shit"],
  ["Seat", "Sit"],
  ["Soup", "Soap"],
  ["Plan", "Plane"],
  ["Road", "Rod"],
  ["Latter", "Ladder", "Later"],
  ["Leader", "Liter"],
  ["Letter", "Litter"],
  ["Ketchup", "Catch up"],
  ["Desert", "Dessert"],
  ["Conform", "Confirm"],
  ["Ask", "Axe"],
  ["Fire", "Fired"],
  ["Older", "Order"],
  ["Man", "Men"],
  ["Woman", "Women"],
  ["Fill", "Feel"],
  ["Breath", "Brief"],
  ["Rid", "Raid"],
  ["Doll", "Dull"],
  ["Ant", "Aunt"],
  ["Fast", "First"],
  ["Coal", "Cool", "Call"],
  ["Meadow", "Medal"],
  ["Show", "Saw"],
  ["So", "Soul"],
  ["No", "Now", "Know"], // Same?
  ["Gone", "Gun"],
  ["Toes", "Those"],
  ["Mess", "Meth"],
  ["Ass", "As"],
  ["Pose", "Pause", "Paws"],
  ["Bag", "Beg"],
  ["Rent", "Rant"],
  ["Does", "Those"],
  ["Chris", "Crease"],
  ["Third", "Turd"],
  ["Ball", "Bowl"],
  ["Broke", "Brooke"],
  ["Broke", "Block"],
  ["Ion", "Iron"],
  ["Eat", "Heat"],
  ["Filling", "Filing"],
  ["Air", "Hair"],
  ["Heal", "Hill"],
  ["Poll", "Paul"],
  ["Sock", "Suck"],
  ["Fox", "Fucks", "Forks"],
  ["Source", "Sauce"],
  ["Chique", "Cheek"],
  ["Discussed", "Disgusted"],
  ["Switch", "Swish"],
  ["Close", "Claws", "Clause", "Clothes"],
  ["Tall", "Toll"],
  ["Atom", "Adam"],
  ["Savor", "Saver"],
  ["meteor", "meatier"],
  ["Russian", "Ration"],
  ["Route", "Root"],
  ["Raider", "Radar"],
  ["Martyr", "Murder"],
  ["Trust", "Thrust"],
  ["List", "Least"],
  ["Take", "Tech"],
  ["Annal", "Anal"],
  ["Sink", "Think"],
  ["Prism", "Prison"],
  ["Cot", "Caught"],
  ["Laugh", "Loaf"],
  ["Knotty", "Naughty"],
  ["Claire", "Clear"],
  ["Shart", "Chart"],
];

const Pairs_new = [
  [{ word: "Lock", phonetic: "lˈɑːk" }, { word: "Rock", phonetic: "ɹˈɑːk" }],
  [{ word: "Wash", phonetic: "wˈɑːʃ" }, { word: "Wish", phonetic: "wˈɪʃ" }],
  [{ word: "Dish", phonetic: "dˈɪʃ" }, { word: "Dash", phonetic: "dˈæʃ" }],
  [{ word: "Lose", phonetic: "lˈuːz" }, { word: "Loose", phonetic: "lˈuːs" }],
  [{ word: "Advice", phonetic: "ɐdvˈaɪs" }, { word: "Advise", phonetic: "ɐdvˈaɪz" }],
  [{ word: "Affect", phonetic: "ɐfˈɛkt" }, { word: "Effect", phonetic: "ɪfˈɛkt" }],
  [{ word: "Compliment", phonetic: "kˈɑːmplɪmənt" }, { word: "Complement", phonetic: "kˈɑːmplɪmənt" }],
  [{ word: "Hang", phonetic: "hˈæŋ" }, { word: "Hung", phonetic: "həŋ" }],
  [{ word: "Price", phonetic: "prīs" }, { word: "Prize", phonetic: "prīz" }],
  [{ word: "Bed", phonetic: "bed" }, { word: "Bad", phonetic: "bad" }],
  [{ word: "Sing", phonetic: "siŋ" }, { word: "Thing", phonetic: "thiŋ" }],
  [{ word: "Sick", phonetic: "sik" }, { word: "Thick", phonetic: "thik" }],
  [{ word: "She", phonetic: "shē" }, { word: "Sea", phonetic: "sē" }],
  [{ word: "Best", phonetic: "best" }, { word: "Vest", phonetic: "vest" }],
  [{ word: "Sue", phonetic: "sü" }, { word: "Shoe", phonetic: "shü" }],
  [{ word: "Glass", phonetic: "glas" }, { word: "Grass", phonetic: "gras" }],
  [{ word: "Hat", phonetic: "hat" }, { word: "Fat", phonetic: "fat" }, { word: "Rat", phonetic: "rat" }],
  [{ word: "Lip", phonetic: "lip" }, { word: "Rip", phonetic: "rip" }],
  [{ word: "Deep", phonetic: "dēp" }, { word: "Dip", phonetic: "dip" }],
  [{ word: "Lice", phonetic: " līs" }, { word: "Rice", phonetic: "rīs" }],
  [{ word: "Right", phonetic: "rīt" }, { word: "Light", phonetic: "līt" }, { word: "Late", phonetic: "lāt" }],
  [{ word: "Long", phonetic: "lȯŋ" }, { word: "Wrong", phonetic: "rȯŋ" }],
  [{ word: "Walk", phonetic: "wȯk" }, { word: "Work", phonetic: "wərk" }],
  [{ word: "Very", phonetic: "ver-ē" }, { word: "Berry", phonetic: "ber-ē" }],
  [{ word: "Fan", phonetic: "fan" }, { word: "Van", phonetic: "van" }, { word: "Ban", phonetic: "ban" }],
  [{ word: "Paper", phonetic: "pā-pər" }, { word: "Pepper", phonetic: "pe-pər" }],
  [{ word: "Ship", phonetic: "ship" }, { word: "Sheep", phonetic: "shēp" }],
  [{ word: "Shit", phonetic: "shit" }, { word: "Sheet", phonetic: "shēt" }],
  [{ word: "Bitch", phonetic: "bich" }, { word: "Beach", phonetic: "bēch" }, { word: "Peach", phonetic: "pēch" }],
  [{ word: "Button", phonetic: "bə-tᵊn" }, { word: "Bottom", phonetic: "bä-təm" }],
  [{ word: "Feel", phonetic: "fēl" }, { word: "Fill", phonetic: "fil" }],
  [{ word: "Bold", phonetic: "bōld" }, { word: "Bald", phonetic: "bȯld" }],
  [{ word: "Trader", phonetic: "trā-dər" }, { word: "Traitor", phonetic: "trā-tər" }],
  [{ word: "Diary", phonetic: "dī-(ə-)rē" }, { word: "Dairy", phonetic: "der-ē" }],
  [{ word: "Chew", phonetic: "chü" }, { word: "Shoe", phonetic: "shü" }],
  [{ word: "Break", phonetic: "brāk" }, { word: "Brake", phonetic: "brāk" }],
  [{ word: "Illusion", phonetic: "i-ˈlü-zhən" }, { word: "Allusion", phonetic: "ə-ˈlü-zhən" }],
  [{ word: "Intention", phonetic: "in-ˈten(t)-shən" }, { word: "Attention", phonetic: "ə-ˈten(t)-shən" }],
];
